package top.ialdaiaxiariyay.rttgtcore.common.machines.machines;

import org.gtlcore.gtlcore.GTLCore;
import org.gtlcore.gtlcore.common.data.GTLBlocks;
import org.gtlcore.gtlcore.common.data.GTLRecipeTypes;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.MachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.CoilWorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.api.recipe.GTRecipe;
import com.gregtechceu.gtceu.api.recipe.OverclockingLogic;
import com.gregtechceu.gtceu.client.util.TooltipHelper;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;
import com.gregtechceu.gtceu.common.data.GTRecipeTypes;
import com.gregtechceu.gtceu.utils.FormattingUtil;

import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.ItemStack;

import appeng.core.AppEng;
import top.ialdaiaxiariyay.rttgtcore.RTTGTCore;
import top.ialdaiaxiariyay.rttgtcore.api.registries.Registration;
import top.ialdaiaxiariyay.rttgtcore.common.data.GetRegistries;
import top.ialdaiaxiariyay.rttgtcore.common.data.RTTGTCreativeModeTabs;
import top.ialdaiaxiariyay.rttgtcore.common.machines.mechanism.RTTGTRecipeModifiers;
import top.ialdaiaxiariyay.rttgtcore.common.machines.mechanism.TheGeneralSteamEngine;
import top.ialdaiaxiariyay.rttgtcore.common.machines.recipes.RTTGTRecipeTypes;

import java.util.List;
import java.util.function.BiConsumer;

import static com.gregtechceu.gtceu.api.pattern.Predicates.blocks;
import static com.gregtechceu.gtceu.api.pattern.util.RelativeDirection.*;
import static com.gregtechceu.gtceu.common.data.GCyMBlocks.*;
import static com.gregtechceu.gtceu.common.data.GCyMRecipeTypes.*;
import static com.gregtechceu.gtceu.common.data.GTBlocks.*;
import static top.ialdaiaxiariyay.rttgtcore.api.registries.Registration.*;

@SuppressWarnings("unused")
public class RTTGTMachines {

    public static final BiConsumer<ItemStack, List<Component>> RTT_ADD = (stack, components) -> components
            .add(Component.translatable("rttgtcore.registry.add")
                    .withStyle(style -> style.withColor(TooltipHelper.RAINBOW_SLOW.getCurrent())));
    static {
        Registration.REGISTRATE.creativeModeTab(() -> RTTGTCreativeModeTabs.MACHINES_ITEM);
    }

    public static void init() {
        RTTGTSmallMachines.init();
    }

    public static final MachineDefinition LARGE_SHAPE_WORLD_VOID_PUMP = REGISTRATE.multiblock("large_shape_world_void_pump", WorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .appearanceBlock(() -> GetRegistries.getBlock("gtceu:stable_machine_casing"))
            .recipeType(RTTGTRecipeTypes.LARGE_SHAPE_WORLD_VOID_PUMP)
            .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK_SUBTICK))
            .tooltips(Component.translatable("block.rttgtcore.large_shape_world_void_pump.tooltip"))
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ")
                    .aisle("           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ")
                    .aisle("                      ", "           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ")
                    .aisle("                      ", "                      ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "         CCCCC        ", "           C          ", "         DDDDD        ", "         DDDDD        ", "         DDDDD        ", "         DDDDD        ", "                      ")
                    .aisle("                      ", "                      ", "                      ", "           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "           C          ", "                      ", "                      ", "           C          ", "                      ", "                      ", "           C          ", "                      ", "                      ", "         CCCCC        ", "                      ", "         DDDDD        ", "       CCDDDDDCC      ", "         DDDDD        ", "       DD     DD      ", "       DD     DD      ", "       DD     DD      ", "       DD     DD      ", "         DDDDD        ")
                    .aisle("                      ", "                      ", "                      ", "                      ", "           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "           C          ", "                      ", "                      ", "           C          ", "                      ", "                      ", "         CCCCC        ", "                      ", "         DDDDD        ", "       CCDDDDDCC      ", "         DDDDD        ", "       DD     DD      ", "      CDDEEEEEDDC     ", "       DD     DD      ", "      D         D     ", "      D         D     ", "      D         D     ", "      DEEEEEEEEED     ", "       DDDDDDDDD      ")
                    .aisle("                      ", "                      ", "                      ", "                      ", "                      ", "           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "           C          ", "                      ", "                      ", "          CCC         ", "                      ", "         DDDDD        ", "        CDDDDDC       ", "         DDDDD        ", "       DD     DD      ", "      CDDEEEEEDDC     ", "       DD     DD      ", "      D         D     ", "     CDEE  E  EEDC    ", "      D         D     ", "     D           D    ", "     D           D    ", "     D           D    ", "     DE    E    ED    ", "      DDDDDDDDDDD     ")
                    .aisle("                      ", "                      ", "                      ", "                      ", "           F          ", "           F          ", "          CFC         ", "           F          ", "           F          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "          CCC         ", "                      ", "          DDD         ", "        CCDDDCC       ", "          DDD         ", "        DD   DD       ", "       CDDEEEDDC      ", "        DD   DD       ", "      DD       DD     ", "     CDDE  E  EDDC    ", "      DD       DD     ", "     D           D    ", "    CDE   EEE   EDC   ", "     D           D    ", "    D             D   ", "    D             D   ", "    D             D   ", "    DE  EEEEEEE  ED   ", "     DDDDDDDDDDDDD    ")
                    .aisle("        D     D       ", "        D     D       ", "        D     D       ", "        D  F  D       ", "        D FEF D       ", "        D F F D       ", "        DCFEFCD       ", "        D F F D       ", "        D FCF D       ", "        D  F  D       ", "        D  C  D       ", "        D  C  D       ", "        D  C  D       ", "        D  C  D       ", "        D  C  D       ", "        DDDDDDD       ", "        CCCCCCC       ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "          DDD         ", "         CDDDC        ", "          DDD         ", "        DD   DD       ", "       CDDEEEDDC      ", "        DD   DD       ", "       D       D      ", "      CDEE E EEDC     ", "       D       D      ", "      D         D     ", "     CDE  EEE  EDC    ", "      D         D     ", "     D           D    ", "    CDE  E E E  EDC   ", "     D           D    ", "    D             D   ", "    D             D   ", "    D             D   ", "    DE EE  E  EE ED   ", "     DDDDDDDDDDDDD    ")
                    .aisle("                      ", "                      ", "           F          ", "          F F         ", "         F E F        ", "         F   F        ", "        CF E FC       ", "         F   F        ", "         F C F        ", "          FFF         ", "                      ", "                      ", "                      ", "                      ", "                      ", "        D     D       ", "        C     C       ", "                      ", "                      ", "                      ", "          DDD         ", "          DDD         ", "          DDD         ", "         D   D        ", "        CDEEEDC       ", "         D   D        ", "        D     D       ", "       CDE E EDC      ", "        D     D       ", "      DD       DD     ", "     CDDE EEE EDDC    ", "      DD       DD     ", "     D           D    ", "    CDE  E E E  EDC   ", "     D           D    ", "    D             D   ", "   CDE  E EEE E  EDC  ", "    D             D   ", "   D               D  ", "   D               D  ", "   D               D  ", "   D E E  EEE  E E D  ", "    DDDDDLLLLLDDDDD   ")
                    .aisle("                      ", "           F          ", "          F F         ", "         FC CF        ", "        F CEC F       ", "        F C C F       ", "       CF CEC FC      ", "        F C C F       ", "        F CCC F       ", "         FFFFF        ", "           F          ", "           F          ", "           F          ", "           F          ", "           F          ", "        D  F  D       ", "        C  D  C       ", "          DDD         ", "          DDD         ", "          DDD         ", "         DDDDD        ", "         D   D        ", "         D E D        ", "        D     D       ", "       CDE E EDC      ", "        D     D       ", "       D       D      ", "      CDE  E  EDC     ", "       D       D      ", "      D         D     ", "     CDE E E E EDC    ", "      D         D     ", "     D           D    ", "    CDE E  E  E EDC   ", "     D           D    ", "    D             D   ", "   CDE E E E E E EDC  ", "    D             D   ", "   D               D  ", "   D               D  ", "   D               D  ", "   D E E E E E E E D  ", "    DDDDDLLLLLDDDDD   ")
                    .aisle("CC         G        CC", " CC       FEF       CC", "  CC     F E F     CC ", "   CC   F  E  F   CC  ", "   CCC FEEEEEEEF CCC  ", "   C CCF   E   FCC C  ", "   C  CFEEEEEEEFC  C  ", "   C   F   E   F   C  ", "   C   FCCCECCCF   C  ", "   C    FFFEFFF    C  ", "   C    C FEF C    C  ", "   C    C FEF C    C  ", "   C    C FEF C    C  ", "   C    C FEF C    C  ", "   C    C FEF C    C  ", "   C    D FEF D    C  ", "   C    C DED C    C  ", "   C      DED      C  ", "   C      DED      C  ", "   C      DED      C  ", "   C     DDEDD     C  ", "   C     D E D     C  ", "   C     DEEED     C  ", "   C    D  E  D    C  ", "   CCCCCDEEEEEDCCCCC  ", "   C    D  E  D    C  ", "   C   D   E   D   C  ", "   CCCCDEEEEEEEDCCCC  ", "   C   D   E   D   C  ", "   C  D    E    D  C  ", "   CCCDEEEEEEEEEDCCC  ", "   C  D    E    D  C  ", "   C D     E     D C  ", "   CCDEEEEEEEEEEEDCC  ", "   C D     E     D C  ", "   CD      E      DC  ", "   CDEEEEEEEEEEEEEDC  ", "   CD      E      DC  ", "   D       E       D  ", "   D       E       D  ", "   D       E       D  ", "   D EEEEEEEEEEEEE D  ", "    DDDDDLL~LLDDDDD   ")
                    .aisle("                      ", "           F          ", "          F F         ", "         FC CF        ", "        F CEC F       ", "        F C C F       ", "       CF CEC FC      ", "        F C C F       ", "        F CCC F       ", "         FFFFF        ", "           F          ", "           F          ", "           F          ", "           F          ", "           F          ", "        D  F  D       ", "        C  D  C       ", "          DDD         ", "          DDD         ", "          DDD         ", "         DDDDD        ", "         D   D        ", "         D E D        ", "        D     D       ", "       CDE E EDC      ", "        D     D       ", "       D       D      ", "      CDE  E  EDC     ", "       D       D      ", "      D         D     ", "     CDE E E E EDC    ", "      D         D     ", "     D           D    ", "    CDE E  E  E EDC   ", "     D           D    ", "    D             D   ", "   CDE E E E E E EDC  ", "    D             D   ", "   D               D  ", "   D               D  ", "   D               D  ", "   D E E E E E E E D  ", "    DDDDDLLLLLDDDDD   ")
                    .aisle("                      ", "                      ", "           F          ", "          F F         ", "         F E F        ", "         F   F        ", "        CF E FC       ", "         F   F        ", "         F C F        ", "          FFF         ", "                      ", "                      ", "                      ", "                      ", "                      ", "        D     D       ", "        C     C       ", "                      ", "                      ", "                      ", "          DDD         ", "          DDD         ", "          DDD         ", "         D   D        ", "        CDEEEDC       ", "         D   D        ", "        D     D       ", "       CDE E EDC      ", "        D     D       ", "      DD       DD     ", "     CDDE EEE EDDC    ", "      DD       DD     ", "     D           D    ", "    CDE  E E E  EDC   ", "     D           D    ", "    D             D   ", "   CDE  E EEE E  EDC  ", "    D             D   ", "   D               D  ", "   D               D  ", "   D               D  ", "   D E E  EEE  E E D  ", "    DDDDDLLLLLDDDDD   ")
                    .aisle("        D     D       ", "        D     D       ", "        D     D       ", "        D  F  D       ", "        D FEF D       ", "        D F F D       ", "        DCFEFCD       ", "        D F F D       ", "        D FCF D       ", "        D  F  D       ", "        D  C  D       ", "        D  C  D       ", "        D  C  D       ", "        D  C  D       ", "        D  C  D       ", "        DDDDDDD       ", "        CCCCCCC       ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "          DDD         ", "         CDDDC        ", "          DDD         ", "        DD   DD       ", "       CDDEEEDDC      ", "        DD   DD       ", "       D       D      ", "      CDEE E EEDC     ", "       D       D      ", "      D         D     ", "     CDE  EEE  EDC    ", "      D         D     ", "     D           D    ", "    CDE  E E E  EDC   ", "     D           D    ", "    D             D   ", "    D             D   ", "    D             D   ", "    DE EE  E  EE ED   ", "     DDDDDDDDDDDDD    ")
                    .aisle("                      ", "                      ", "                      ", "                      ", "           F          ", "           F          ", "          CFC         ", "           F          ", "           F          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "          CCC         ", "                      ", "          DDD         ", "        CCDDDCC       ", "          DDD         ", "        DD   DD       ", "       CDDEEEDDC      ", "        DD   DD       ", "      DD       DD     ", "     CDDE  E  EDDC    ", "      DD       DD     ", "     D           D    ", "    CDE   EEE   EDC   ", "     D           D    ", "    D             D   ", "    D             D   ", "    D             D   ", "    DE  EEEEEEE  ED   ", "     DDDDDDDDDDDDD    ")
                    .aisle("                      ", "                      ", "                      ", "                      ", "                      ", "           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "           C          ", "                      ", "                      ", "          CCC         ", "                      ", "         DDDDD        ", "        CDDDDDC       ", "         DDDDD        ", "       DD     DD      ", "      CDDEEEEEDDC     ", "       DD     DD      ", "      D         D     ", "     CDEE  E  EEDC    ", "      D         D     ", "     D           D    ", "     D           D    ", "     D           D    ", "     DE    E    ED    ", "      DDDDDDDDDDD     ")
                    .aisle("                      ", "                      ", "                      ", "                      ", "           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "           C          ", "                      ", "                      ", "           C          ", "                      ", "                      ", "         CCCCC        ", "                      ", "         DDDDD        ", "       CCDDDDDCC      ", "         DDDDD        ", "       DD     DD      ", "      CDDEEEEEDDC     ", "       DD     DD      ", "      D         D     ", "      D         D     ", "      D         D     ", "      DEEEEEEEEED     ", "       DDDDDDDDD      ")
                    .aisle("                      ", "                      ", "                      ", "           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "           C          ", "                      ", "                      ", "           C          ", "                      ", "                      ", "           C          ", "                      ", "                      ", "         CCCCC        ", "                      ", "         DDDDD        ", "       CCDDDDDCC      ", "         DDDDD        ", "       DD     DD      ", "       DD     DD      ", "       DD     DD      ", "       DD     DD      ", "         DDDDD        ")
                    .aisle("                      ", "                      ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "           C          ", "         CCCCC        ", "           C          ", "         DDDDD        ", "         DDDDD        ", "         DDDDD        ", "         DDDDD        ", "                      ")
                    .aisle("                      ", "           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ")
                    .aisle("           C          ", "           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ")
                    .aisle("           C          ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ", "                      ")
                    .where('~', Predicates.controller(blocks(definition.getBlock())))
                    .where(' ', Predicates.any())
                    .where("C", Predicates.blocks(GetRegistries.getBlock("gtceu:stainless_steel_frame")))
                    .where("D", Predicates.blocks(GetRegistries.getBlock("gtceu:stable_machine_casing")))
                    .where("L", Predicates.blocks(GetRegistries.getBlock("gtceu:stable_machine_casing"))
                            .setMinGlobalLimited(10)
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)))
                    .where("E", Predicates.blocks(GetRegistries.getBlock("gtceu:ptfe_pipe_casing")))
                    .where("F", Predicates.blocks(GetRegistries.getBlock("gtceu:ev_machine_casing")))
                    .where("G", Predicates.blocks(GetRegistries.getBlock("rttgtcore:void_world_block")))
                    .build())
            .workableCasingRenderer(GTCEu.id("block/casings/solid/machine_casing_stable_titanium"),
                    GTCEu.id("block/multiblock/cleanroom"), false)
            .register();

    public static final MachineDefinition Compressed_Block_Transmutation_Chamber = REGISTRATE.multiblock("compressed_block_transmutation_chamber", WorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .appearanceBlock(() -> GetRegistries.getBlock("gtlcore:aluminium_bronze_casing"))
            .recipeType(RTTGTRecipeTypes.Compressed_Block_Transmutation_Chamber)
            .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK_SUBTICK))
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("AAAAA", "AAAAA", "BBBBB", "BBBBB", "AAAAA", "AAAAA")
                    .aisle("AAAAA", "ACCCA", "B   B", "B   B", "ACCCA", "AAAAA")
                    .aisle("AAAAA", "ACCCA", "B A B", "B A B", "ACCCA", "AA~AA")
                    .aisle("AAAAA", "ACCCA", "B   B", "B   B", "ACCCA", "AAAAA")
                    .aisle("AAAAA", "AAAAA", "BBBBB", "BBBBB", "AAAAA", "AAAAA")
                    .where("~", Predicates.controller(Predicates.blocks(definition.get())))
                    .where("A", Predicates.blocks(GetRegistries.getBlock("gtlcore:aluminium_bronze_casing"))
                            .setMinGlobalLimited(10)
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)))
                    .where("C", Predicates.blocks(GetRegistries.getBlock("kubejs:shining_obsidian")))
                    .where("B", Predicates.blocks(GetRegistries.getBlock("gtceu:tempered_glass")))
                    .build())
            .workableCasingRenderer(RTTGTCore.id("block/casings/aluminium_bronze_casing"),
                    GTCEu.id("block/multiblock/cleanroom"), false)
            .tooltips(Component.translatable("block.rttgtcore.compressed_block_transmutation_chamber.tooltip"))
            .register();

    public static final MachineDefinition THERMOMAGNETIC_COOLING_GENERATOR = REGISTRATE.multiblock("thermomagnetic_cooling_generator", WorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .appearanceBlock(() -> GetRegistries.getBlock("gtceu:lv_machine_casing"))
            .recipeType(RTTGTRecipeTypes.THERMOMAGNETIC_COOLING_GENERATOR)
            .recipeModifier((machine, recipe, params, result) -> RTTGTRecipeModifiers.standardOverclocking((WorkableElectricMultiblockMachine) machine, recipe))
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("     ", " AAA ", " ABA ", " AAA ", "     ", "     ", "     ")
                    .aisle(" AAA ", "A D A", "ACECA", "A D A", " AAA ", "     ", "     ")
                    .aisle(" AAA ", "A D A", "ACECA", "A D A", " AAA ", "     ", "     ")
                    .aisle(" AAA ", "A D A", "ACECA", "A D A", " ABA ", "  B  ", "  B  ")
                    .aisle(" AAA ", "A D A", "ACECA", "A D A", " AAA ", "     ", "  B  ")
                    .aisle(" AAA ", "A D A", "ACECA", "A D A", " AAA ", "     ", "  B  ")
                    .aisle("     ", " AAA ", " ABA ", " AAA ", "     ", "     ", "  B  ")
                    .aisle("     ", " BBB ", " B~B ", " BBB ", "  B  ", "  B  ", "  B  ")
                    .where("~", Predicates.controller(Predicates.blocks(definition.get())))
                    .where("B", Predicates.blocks(GetRegistries.getBlock("gtceu:lv_machine_casing"))
                            .setMinGlobalLimited(10)
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.OUTPUT_ENERGY).setMaxGlobalLimited(2)))
                    .where("E", Predicates.blocks(GetRegistries.getBlock("minecraft:redstone_block")))
                    .where("D", Predicates.blocks(GetRegistries.getBlock("minecraft:blue_ice")))
                    .where("A", Predicates.blocks(GetRegistries.getBlock("minecraft:iron_block")))
                    .where("C", Predicates.blocks(GetRegistries.getBlock("minecraft:magma_block")))
                    .build())
            .workableCasingRenderer(GTCEu.id("block/casings/voltage/lv/side"),
                    GTCEu.id("block/multiblock/fusion_reactor"), false)
            .tooltips(Component.translatable("block.rttgtcore.thermomagnetic_cooling_generator.tooltip"))
            .register();

    public static final MachineDefinition GENERAL_ENERGY_FURNACE = REGISTRATE.multiblock("general_energy_furnace", WorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .appearanceBlock(CASING_HIGH_TEMPERATURE_SMELTING)
            .recipeType(GTRecipeTypes.BLAST_RECIPES)
            .recipeType(ALLOY_BLAST_RECIPES)
            .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK_SUBTICK))
            .recipeModifier((machine, recipe, params, result) -> {
                GTRecipe recipe1 = recipe.copy();
                recipe1.duration = 0;
                recipe1 = GTRecipeModifiers.fastParallel(machine, recipe1, 2147483647, false).getFirst();
                return recipe1;
            })
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaa", "ccccccc", "ccccccc", "ccccccc", "eeeeeee", "ccccccc", "ccccccc", "ccccccc", "aaaaaaa")
                    .aisle("aaaaaaa", "c     c", "c     c", "c     c", "e     e", "c     c", "c     c", "c     c", "aaaaaaa")
                    .aisle("aaaaaaa", "c     c", "c     c", "c     c", "e     e", "c     c", "c     c", "c     c", "aaaaaaa")
                    .aisle("aaaaaaa", "c     c", "c     c", "c     c", "e  f  e", "c     c", "c     c", "c     c", "aaaaaaa")
                    .aisle("aaaaaaa", "c     c", "c     c", "c     c", "e     e", "c     c", "c     c", "c     c", "aaaaaaa")
                    .aisle("aaaaaaa", "c     c", "c     c", "c     c", "e     e", "c     c", "c     c", "c     c", "aaaaaaa")
                    .aisle("aaa~aaa", "ccccccc", "ccccccc", "ccccccc", "eeeeeee", "ccccccc", "ccccccc", "ccccccc", "aaaaaaa")
                    .where('~', Predicates.controller(blocks(definition.getBlock())))
                    .where(' ', Predicates.any())
                    .where("c", Predicates.blocks(GetRegistries.getBlock("gtceu:cleanroom_glass")))
                    .where("a", Predicates.blocks(GetRegistries.getBlock("gtceu:high_temperature_smelting_casing"))
                            .setMinGlobalLimited(10)
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)))
                    .where("e", Predicates.blocks(GetRegistries.getBlock("gtceu:heat_vent")))
                    .where("f", Predicates.heatingCoils())
                    .build())
            .workableCasingRenderer(GTCEu.id("block/casings/gcym/high_temperature_smelting_casing"),
                    GTCEu.id("block/multiblock/fusion_reactor"), false)
            .tooltips(Component.translatable("block.rttgtcore.general_energy_furnace.tooltip"))
            .register();

    public static final MachineDefinition FIGURE_FACTORY = REGISTRATE.multiblock("figure_factory", WorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .appearanceBlock(GTLBlocks.DIMENSIONALLY_TRANSCENDENT_CASING)
            .recipeType(RTTGTRecipeTypes.FIGURE_FACTORY)
            .recipeModifiers(GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK_SUBTICK))
            .recipeModifier((machine, recipe, params, result) -> {
                GTRecipe recipe1 = recipe.copy();
                recipe1 = GTRecipeModifiers.fastParallel(machine, recipe1, 64, false).getFirst();
                return recipe1;
            })
            .tooltips(Component.translatable("block.rttgtcore.figure_factory.tooltip.1"))
            .tooltips(Component.translatable("block.rttgtcore.figure_factory.tooltip.2"))
            .tooltips(Component.translatable("block.rttgtcore.figure_factory.tooltip.3"))
            .tooltips(Component.translatable("block.rttgtcore.figure_factory.tooltip.4"))
            .tooltips(Component.translatable("block.rttgtcore.figure_factory.tooltip.5"))
            .pattern(definition -> FactoryBlockPattern.start(FRONT, UP, LEFT)
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AAAAAAAAAAAAAAAAAAAAA", "                     ", "                     ", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "ACCCCCCCCCCCCCCCCCCCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACCCCCCCCCCCCCCCCCCCA", "ADDDDDDDDDDDDDDDDDDDA", "                     ", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B D   D   D   D   D B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "                     ", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B D   D   D   D   D B", "B D   D   D   D   D B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "ADDDDDDDDDDDDDDDDDDDA", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B                   B", "B D   D   D   D   D B", "B D   D   D   D   D B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B                   B", "B                   B", "B D   D   D   D   D B", "B D   D   D   D   D B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "ADDDDDDDDDDDDDDDDDDDA", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B G   G   G   G   G B", "B G   G   G   G   G B", "B G   G   G   G   G B", "B D F D F D F D F D B", "B D   D   D   D   D B", "B                   B", "B                   B", "B                   B", "B H   H   H   H   H B", "B H   H   H   H   H B", "B H   H   H   H   H B", "ADDDDDDDDDDDDDDDDDDDA", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B                   B", "B                   B", "B                   B", "B                   B", "B I   I   I   I   I B", "B                   B", "B                   B", "B H   H   H   H   H B", "B H   H   H   H   H B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "ADDDJDDDJDDDJDDDJDDDA")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B  KKFFKKFFKKFFKKFFKK", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B H   H   H   H   H B", "B H   H   H   H   H B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDJDJDJDJDJDJDJDJDDA")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "LKKIIKKIIKKIIKKIIKKFB", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B H   H   H   H   H B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDJDDDJDDDJDDDJDDDA")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "LKKKKKKKKKKKKKKKKKKKB", "B K   K   K   K   K B", "B K   K   K   K   K B", "B K   K   K   K   K B", "B M   M   M   M   M B", "B                   B", "B J F J F J F J F J B", "B                   B", "B F   F   F   F   F B", "B F   F   F   F   F B", "B F   F   F   F   F B", "B F   F   F   F   F B", "AJJJJJJJJJJJJJJJJJJJ~")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "LKKIIKKIIKKIIKKIIKKFB", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B H   H   H   H   H B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDJDDDJDDDJDDDJDDDA")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B  KKFFKKFFKKFFKKFFKK", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B H   H   H   H   H B", "B H   H   H   H   H B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDJDJDJDJDJDJDJDJDDA")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B                   B", "B                   B", "B                   B", "B                   B", "B I   I   I   I   I B", "B                   B", "B                   B", "B H   H   H   H   H B", "B H   H   H   H   H B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "ADDDJDDDJDDDJDDDJDDDA")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B G   G   G   G   G B", "B G   G   G   G   G B", "B G   G   G   G   G B", "B E   E   E   E   E B", "B E   E   E   E   E B", "B                   B", "B                   B", "B                   B", "B H   H   H   H   H B", "B H   H   H   H   H B", "B H   H   H   H   H B", "ADDDDDDDDDDDDDDDDDDDA", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B                   B", "B                   B", "B E   E   E   E   E B", "B E F E F E F E F E B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "ADDDDDDDDDDDDDDDDDDDA", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B                   B", "B E   E   E   E   E B", "B E   E   E   E   E B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B E   E   E   E   E B", "B E   E   E   E   E B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "ADDDDDDDDDDDDDDDDDDDA", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "B E   E   E   E   E B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "B                   B", "ADDDDDDDDDDDDDDDDDDDA", "                     ", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "ACCCCCCCCCCCCCCCCCCCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACBBBBBBBBBBBBBBBBBCA", "ACCCCCCCCCCCCCCCCCCCA", "ADDDDDDDDDDDDDDDDDDDA", "                     ", "                     ", "                     ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AABBBBBBBBBBBBBBBBBAA", "AAAAAAAAAAAAAAAAAAAAA", "                     ", "                     ", "                     ", "                     ")
                    .where("~", Predicates.controller(Predicates.blocks(definition.get())))
                    .where("G", Predicates.blocks(GetRegistries.getBlock("gtceu:magnetohydrodynamicallyconstrainedstarmatter_frame")))
                    .where("J", Predicates.blocks(GetRegistries.getBlock("gtlcore:component_assembly_line_casing_max")))
                    .where("L", Predicates.blocks(GetRegistries.getBlock("gtlcore:dimensionally_transcendent_casing"))
                            .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1)))
                    .where("M", Predicates.blocks(GetRegistries.getBlock("kubejs:create_aggregatione_core")))
                    .where("E", Predicates.blocks(GetRegistries.getBlock("gtlcore:molecular_casing")))
                    .where("H", Predicates.blocks(GetRegistries.getBlock("kubejs:neutronium_pipe_casing")))
                    .where("F", Predicates.blocks(GetRegistries.getBlock("kubejs:dimension_creation_casing")))
                    .where("K", Predicates.blocks(GetRegistries.getBlock("gtlcore:create_casing")))
                    .where("B", Predicates.blocks(GetRegistries.getBlock("gtlcore:infinity_glass")))
                    .where("C", Predicates.blocks(GetRegistries.getBlock("gtlcore:manipulator")))
                    .where("A", Predicates.blocks(GetRegistries.getBlock("gtlcore:dimensionally_transcendent_casing")))
                    .where("D", Predicates.blocks(GetRegistries.getBlock("gtlcore:dimension_connection_casing")))
                    .where("I", Predicates.blocks(GetRegistries.getBlock("kubejs:create_hpca_component")))
                    .where(' ', Predicates.any())
                    .build())
            .workableCasingRenderer(GTLCore.id("block/casings/dimensionally_transcendent_casing"),
                    GTCEu.id("block/multiblock/fusion_reactor"))
            .register();

    public static final MachineDefinition DIMENSIONALLY_TRANSCENDENT_PLASMA_FORGE_MK1 = REGISTRATE.multiblock("dimensionally_transcendent_plasma_forge_mk1", CoilWorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .allowExtendedFacing(false)
            .recipeType(GTLRecipeTypes.DIMENSIONALLY_TRANSCENDENT_PLASMA_FORGE_RECIPES)
            .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK_SUBTICK))
            .recipeModifier((machine, recipe, params, result) -> {
                GTRecipe recipe1 = recipe.copy();
                recipe1.duration = 0;
                return recipe1;
            })
            .appearanceBlock(GTLBlocks.DIMENSIONALLY_TRANSCENDENT_CASING)
            .tooltips(Component.translatable("gtceu.machine.available_recipe_map_1.tooltip",
                    Component.translatable("gtceu.dimensionally_transcendent_plasma_forge")))
            .tooltips(Component.translatable("block.rttgtcore.dtpf.tooltip.1"))
            .tooltips(Component.translatable("block.rttgtcore.dtpf.tooltip.2"))
            .tooltips(Component.translatable("block.rttgtcore.dtpf.tooltip.3"))
            .tooltips(Component.translatable("block.rttgtcore.dtpf.tooltip.4"))
            .tooltipBuilder(RTT_ADD)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("AAAA   AAA   AAA   AAA   AAA   AAAA", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", "                                   ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", " ACA   ACA   ACA   ACA   ACA   ACA ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", " ACA   ACA   ACA   ACA   ACA   ACA ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", " AAA                           AAA ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " AAA   AAA   AAA   AAA   AAA   AAA ", "  D     D     D     D     D     D  ", " AAA   AAA   AAA   AAA   AAA   AAA ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " AAA   AAA   AAA   AAA   AAA   AAA ", " CDCADACDCADACDCADACDCADACDCADACDC ", " AAA   AAA   AAA   AAA   AAA   AAA ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " AAA   AAA   AAA   AAA   AAA   AAA ", " CDCADACDCADACDCADACDCADACDCADACDC ", " AAA   AAA   AAA   AAA   AAA   AAA ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " AAA   AAA   AAA   AAA   AAA   AAA ", "  D     D     D     D     D     D  ", "  A     A     A     A     A     A  ", " ADAAAAADAAAAADAAAAADAAAAADAAAAADA ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", "                                   ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", " ACA   ACA   ACA   ACA   ACA   ACA ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", " ACA   ACA   ACA   ACA   ACA   ACA ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", " AAA  AAAAA   ADADADA   AAAAA  AAA ")
                    .aisle(" AAA   AAA   AAA   AAA   AAA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A    AAA     AAAAA     AAA    A  ")
                    .aisle(" AAA   AAA   AAA   AAA   AAA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  D     D     D     D     D     D  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  D     D     D     D     D     D  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A       AAA       A     A  ")
                    .aisle(" AAA   AAA   AAA   AAA   AAA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  AA    A      AAAAA      A    AA  ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BBB    A     A     A     A    BBB ", " BBB                           BBB ", " BBB    A     A     A     A    BBB ", "  A    BBB   BBB   BBB   BBB    A  ", "       BBB   BBB   BBB   BBB       ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A                             A  ", "                                   ", "                                   ", "  AAA   A     AAAAAAA     A   AAA  ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BCB   AAA   AAA   AAA   AAA   BCB ", " BCB    D     D     D     D    BCB ", " BCB   AAA   AAA   AAA   AAA   BCB ", " AAA   BCB   BCB   BCB   BCB   AAA ", "  D    BCB   BCB   BCB   BCB    D  ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " BCB    A     A     A     A    BCB ", " AAA   BBB   BBB   BBB   BBB   AAA ", " CDCADACCCADACCCADACCCADACCCADACDC ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " BCB    A     A     A     A    BCB ", " AAA   BCB   BCB   BCB   BCB   AAA ", " CDCADACCCADACCCADACCCADACCCADACDC ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " AAA    D     D     D     D    AAA ", "  D     A     A     A     A     D  ", "  A     A     A     A     A     A  ", "  DAAAAADAAAAAAADADAAAAAAADAAAAAD  ")
                    .aisle("AAAAAAAAAA   AAAAAAAAA   AAAAAAAAAA", " BBB    A     A     A     A    BBB ", " BBB                           BBB ", " BBB    A     A     A     A    BBB ", "  A    BBB   BBB   BBB   BBB    A  ", "       BBB   BBB   BBB   BBB       ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A                             A  ", "                                   ", "                                   ", "  AAA   A     AAAAAAA     A   AAA  ")
                    .aisle(" AAA   AA     AACCCAA     AA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  AA    A      AAAAA      A    AA  ")
                    .aisle(" AAA   AA     CCCCCCC     AA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  D     D     D     D     D     D  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  D     D     D     D     D     D  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A       AAA       A     A  ")
                    .aisle(" AAA   AA    CCCCCCCCC    AA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A        A        A     A  ")
                    .aisle("AAAAAAAAAA  CCACCCCCACC  AAAAAAAAAA", " BBB    A     A     A     A    BBB ", " BBB                           BBB ", " BBB    A     A     A     A    BBB ", "  A    BBB   BBB   BBB   BBB    A  ", "       BBB   BBB   BBB   BBB       ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A                             A  ", "                                   ", "                                   ", "  A     A       AAA       A     A  ")
                    .aisle("AAAAAAAAAAACCAAACCCAAACCAAAAAAAAAAA", " BCB   AAA   AAA   AAA   AAA   BCB ", " BCB    D     D     D     D    BCB ", " BCB   AAA   AAA   AAA   AAA   BCB ", " AAA   BCB   BCB   BCB   BCB   AAA ", "  D    BCB   BCB   BCB   BCB    D  ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " BCB    A     A     A     A    BCB ", " AAA   BBB   BBB   BBB   BBB   AAA ", " CDCADACCCADACCCADACCCADACCCADACDC ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " BCB    A     A     A     A    BCB ", " AAA   BCB   BCB   BCB   BCB   AAA ", " CDCADACCCADACCCADACCCADACCCADACDC ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " AAA    D     D     D     D    AAA ", "  D     A     A     A     A     D  ", "  A     A     A     A     A     A  ", "  DA   AAA    AAAAAAA    AAA   AD  ")
                    .aisle("AAAAAAAAAAACCCACAAACACCCAAAAAAAAAAA", " BBB    A     A AAA A     A    BBB ", " BBB                           BBB ", " BBB    A     A     A     A    BBB ", "  A    BBB   BBB   BBB   BBB    A  ", "       BBB   BBB   BBB   BBB       ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A                             A  ", "                                   ", "                                   ", "  ADA AAAAA   A  A  A   AAAAA ADA  ")
                    .aisle(" AAA   AAACCCCCAAAAACCCCCAAA   AAA ", "               AAAAA               ", "                EEE                ", "                EEE                ", "                EEE                ", "                 A                 ", "                                   ", "                 A                 ", "                 G                 ", "                 G                 ", "                 G                 ", "  A     A     A  G  A     A     A  ", "                 G                 ", "                 A                 ", "                 G                 ", "                 G                 ", "                 G                 ", "  A     A     A  G  A     A     A  ", "                 G                 ", "                 A                 ", "                 G                 ", "                 G                 ", "                 G                 ", "                 G                 ", "                 G                 ", "  AAAAAADAAA AA  A  AA AAADAAAAAA  ")
                    .aisle(" AAA   AAACCCCCAAAAACCCCCAAA   AAA ", "               AAAAA               ", "                EDE                ", "                EDE                ", "                EDE                ", "                ADA                ", "                 D                 ", "                AAA                ", "                GCG                ", "                GCG                ", "                GCG                ", "  D     D     D GCG D     D     D  ", "                GDG                ", "                AAA                ", "                GCG                ", "                GCG                ", "                GCG                ", "  D     D     D GCG D     D     D  ", "                GDG                ", "                AAA                ", "                GCG                ", "                GCG                ", "                GCG                ", "                GCG                ", "                GDG                ", "  ADAAAAAAAAAAAAAAAAAAAAAAAAAAADA  ")
                    .aisle(" AAA   AAACCCCCAAAAACCCCCAAA   AAA ", "               AAAAA               ", "                EEE                ", "                E~E                ", "                EEE                ", "                 A                 ", "                                   ", "                 A                 ", "                 G                 ", "                 G                 ", "                 G                 ", "  A     A     A  G  A     A     A  ", "                 G                 ", "                 A                 ", "                 G                 ", "                 G                 ", "                 G                 ", "  A     A     A  G  A     A     A  ", "                 G                 ", "                 A                 ", "                 G                 ", "                 G                 ", "                 G                 ", "                 G                 ", "                 G                 ", "  AAAAAADAAA AA  A  AA AAADAAAAAA  ")
                    .aisle("AAAAAAAAAAACCCACAAACACCCAAAAAAAAAAA", " BBB    A     A AAA A     A    BBB ", " BBB                           BBB ", " BBB    A     A     A     A    BBB ", "  A    BBB   BBB   BBB   BBB    A  ", "       BBB   BBB   BBB   BBB       ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A                             A  ", "                                   ", "                                   ", "  ADA AAAAA   A  A  A   AAAAA ADA  ")
                    .aisle("AAAAAAAAAAACCAAACCCAAACCAAAAAAAAAAA", " BCB   AAA   AAA   AAA   AAA   BCB ", " BCB    D     D     D     D    BCB ", " BCB   AAA   AAA   AAA   AAA   BCB ", " AAA   BCB   BCB   BCB   BCB   AAA ", "  D    BCB   BCB   BCB   BCB    D  ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " BCB    A     A     A     A    BCB ", " AAA   BBB   BBB   BBB   BBB   AAA ", " CDCADACCCADACCCADACCCADACCCADACDC ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " BCB    A     A     A     A    BCB ", " AAA   BCB   BCB   BCB   BCB   AAA ", " CDCADACCCADACCCADACCCADACCCADACDC ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " AAA    D     D     D     D    AAA ", "  D     A     A     A     A     D  ", "  A     A     A     A     A     A  ", "  DA   AAA    AAAAAAA    AAA   AD  ")
                    .aisle("AAAAAAAAAA  CCACCCCCACC  AAAAAAAAAA", " BBB    A     A     A     A    BBB ", " BBB                           BBB ", " BBB    A     A     A     A    BBB ", "  A    BBB   BBB   BBB   BBB    A  ", "       BBB   BBB   BBB   BBB       ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A                             A  ", "                                   ", "                                   ", "  A     A       AAA       A     A  ")
                    .aisle(" AAA   AA    CCCCCCCCC    AA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A        A        A     A  ")
                    .aisle(" AAA   AA     CCCCCCC     AA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  D     D     D     D     D     D  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  D     D     D     D     D     D  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A       AAA       A     A  ")
                    .aisle(" AAA   AA     AACCCAA     AA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  AA    A      AAAAA      A    AA  ")
                    .aisle("AAAAAAAAAA   AAAAAAAAA   AAAAAAAAAA", " BBB    A     A     A     A    BBB ", " BBB                           BBB ", " BBB    A     A     A     A    BBB ", "  A    BBB   BBB   BBB   BBB    A  ", "       BBB   BBB   BBB   BBB       ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A                             A  ", "                                   ", "                                   ", "  AAA   A     AAAAAAA     A   AAA  ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BCB   AAA   AAA   AAA   AAA   BCB ", " BCB    D     D     D     D    BCB ", " BCB   AAA   AAA   AAA   AAA   BCB ", " AAA   BCB   BCB   BCB   BCB   AAA ", "  D    BCB   BCB   BCB   BCB    D  ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " BCB    A     A     A     A    BCB ", " AAA   BBB   BBB   BBB   BBB   AAA ", " CDCADACCCADACCCADACCCADACCCADACDC ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " BCB    A     A     A     A    BCB ", " AAA   BCB   BCB   BCB   BCB   AAA ", " CDCADACCCADACCCADACCCADACCCADACDC ", " AAA   BCB   BCB   BCB   BCB   AAA ", " BCB    A     A     A     A    BCB ", " BCB    A     A     A     A    BCB ", " BCB    D     D     D     D    BCB ", " AAA    D     D     D     D    AAA ", "  D     A     A     A     A     D  ", "  A     A     A     A     A     A  ", "  DAAAAADAAAAAAADADAAAAAAADAAAAAD  ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BBB    A     A     A     A    BBB ", " BBB                           BBB ", " BBB    A     A     A     A    BBB ", "  A    BBB   BBB   BBB   BBB    A  ", "       BBB   BBB   BBB   BBB       ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A    BBB   BBB   BBB   BBB    A  ", " ACA   BCB   BCB   BCB   BCB   ACA ", "  A    BBB   BBB   BBB   BBB    A  ", " BBB                           BBB ", " BBB                           BBB ", " BBB                           BBB ", "  A                             A  ", "                                   ", "                                   ", "  AAA   A     AAAAAAA     A   AAA  ")
                    .aisle(" AAA   AAA   AAA   AAA   AAA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  AA    A      AAAAA      A    AA  ")
                    .aisle(" AAA   AAA   AAA   AAA   AAA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  D     D     D     D     D     D  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  D     D     D     D     D     D  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A       AAA       A     A  ")
                    .aisle(" AAA   AAA   AAA   AAA   AAA   AAA ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "  A    AAA     AAAAA     AAA    A  ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", "                                   ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", " ACA   ACA   ACA   ACA   ACA   ACA ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", " ACA   ACA   ACA   ACA   ACA   AC  ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", " AAA  AAAAA   ADADADA   AAAAA  AAA ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " AAA   AAA   AAA   AAA   AAA   AAA ", "  D     D     D     D     D     D  ", " AAA   AAA   AAA   AAA   AAA   AAA ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " AAA   AAA   AAA   AAA   AAA   AAA ", " CDCADACDCADACDCADACDCADACDCADACDC ", " AAA   AAA   AAA   AAA   AAA   AAA ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " AAA   AAA   AAA   AAA   AAA   AAA ", " CDCADACDCADACDCADACDCADACDCADACDC ", " AAA   AAA   AAA   AAA   AAA   AAA ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " BCB   BCB   BCB   BCB   BCB   BCB ", " AAA   AAA   AAA   AAA   AAA   AAA ", "  D     D     D     D     D     D  ", "  A     A     A     A     A     A  ", " ADAAAAADAAAAADAAAAADAAAAADAAAAADA ")
                    .aisle("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", "                                   ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", " ACA   ACA   ACA   ACA   ACA   ACA ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", " ACA   ACA   ACA   ACA   ACA   ACA ", "  A     A     A     A     A     A  ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", " BBB   BBB   BBB   BBB   BBB   BBB ", "  A     A     A     A     A     A  ", "                                   ", "                                   ", " AAA                           AAA ")
                    .aisle("AAAA   AAA   AAA   AAA   AAA   AAAA", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ", "                                   ")
                    .where("~", Predicates.controller(Predicates.blocks(definition.get())))
                    .where("C", Predicates.blocks(GTLBlocks.DIMENSION_INJECTION_CASING.get()))
                    .where("G", Predicates.blocks(GetRegistries.getBlock("gtlcore:rhenium_reinforced_energy_glass")))
                    .where("D", Predicates.blocks(GetRegistries.getBlock("kubejs:dimensional_bridge_casing")))
                    .where("B", Predicates.heatingCoils())
                    .where("A", Predicates.blocks(GTLBlocks.DIMENSIONALLY_TRANSCENDENT_CASING.get()))
                    .where("E", Predicates.blocks(GTLBlocks.DIMENSIONALLY_TRANSCENDENT_CASING.get())
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                            .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(1)))
                    .build())
            .beforeWorking((machine, recipe) -> {
                if (machine instanceof CoilWorkableElectricMultiblockMachine coilWorkableElectricMultiblockMachine) {
                    if (coilWorkableElectricMultiblockMachine.getCoilType().getCoilTemperature() == 273) {
                        if (machine.getRecipeType() == GTLRecipeTypes.STELLAR_FORGE_RECIPES) {
                            return true;
                        } else if (recipe.data.getInt("ebf_temp") <= 32000) {
                            return true;
                        }
                    } else if (recipe.data.getInt("ebf_temp") <= coilWorkableElectricMultiblockMachine.getCoilType().getCoilTemperature()) {
                        return true;
                    }
                }
                machine.getRecipeLogic().interruptRecipe();
                return false;
            })
            .additionalDisplay((controller, components) -> {
                if (controller.isFormed() && controller instanceof CoilWorkableElectricMultiblockMachine machine) {
                    int temp = machine.getCoilType().getCoilTemperature();
                    components.add(Component.translatable("gtceu.multiblock.blast_furnace.max_temperature", Component.literal(FormattingUtil.formatNumbers((temp == 273 ? 32000 : temp)) + "K").withStyle(ChatFormatting.BLUE)));
                }
            })
            .workableCasingRenderer(GTLCore.id("block/casings/dimensionally_transcendent_casing"), GTCEu.id("block/multiblock/dimensionally_transcendent_plasma_forge"))
            .register();

    public static final MachineDefinition THE_GENERAL_STEAM_ENGINE = REGISTRATE.multiblock("the_general_steam_engine", holder -> new TheGeneralSteamEngine(holder, 4096))
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(GTLRecipeTypes.LAVA_FURNACE_RECIPES)
            .recipeType(GTRecipeTypes.FORGE_HAMMER_RECIPES)
            .recipeType(GTRecipeTypes.COMPRESSOR_RECIPES)
            .recipeType(GTRecipeTypes.ALLOY_SMELTER_RECIPES)
            .recipeType(GTRecipeTypes.MACERATOR_RECIPES)
            .recipeType(GTRecipeTypes.CIRCUIT_ASSEMBLER_RECIPES)
            .recipeType(GTRecipeTypes.MIXER_RECIPES)
            .recipeType(GTRecipeTypes.CENTRIFUGE_RECIPES)
            .recipeType(GTRecipeTypes.THERMAL_CENTRIFUGE_RECIPES)
            .recipeType(GTRecipeTypes.CHEMICAL_BATH_RECIPES)
            .recipeType(GTRecipeTypes.ORE_WASHER_RECIPES)
            .recipeType(GTRecipeTypes.LARGE_BOILER_RECIPES)
            .recipeType(GTRecipeTypes.FURNACE_RECIPES)
            .recipeType(GTRecipeTypes.EXTRACTOR_RECIPES)
            .appearanceBlock(() -> GetRegistries.getBlock("gtceu:steam_machine_casing"))
            .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK_SUBTICK))
            .recipeModifier((machine, recipe, params, result) -> {
                GTRecipe recipe1 = recipe.copy();
                recipe1.duration = 0;
                recipe1 = GTRecipeModifiers.fastParallel(machine, recipe1, 4096, false).getFirst();
                return recipe1;
            })
            .tooltips(Component.translatable("block.rttgtcore.the_general_steam_engine.tooltip.1"))
            .tooltips(Component.translatable("block.rttgtcore.the_general_steam_engine.tooltip.2"))
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("AAAAA", "A A A", "AA AA", "A A A", "AAAAA")
                    .aisle("AAAAA", "     ", "A   A", "     ", "AAAAA")
                    .aisle("AAAAA", "A A A", "  B  ", "A A A", "AAAAA")
                    .aisle("AAAAA", "     ", "A   A", "     ", "AAAAA")
                    .aisle("AA~AA", "A A A", "AA AA", "A A A", "AAAAA")
                    .where("~", Predicates.controller(Predicates.blocks(definition.get())))
                    .where("B", Predicates.blocks(GetRegistries.getBlock("rttgtcore:void_world_block")))
                    .where("A", Predicates.blocks(GetRegistries.getBlock("gtceu:steam_machine_casing"))
                            .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.STEAM).setExactLimit(1)))
                    .build())
            .workableCasingRenderer(GTCEu.id("block/casings/solid/machine_casing_bronze_plated_bricks"), GTCEu.id("block/multiblock/steam_oven"))
            .register();

    public static final MachineDefinition GENERAL_AE_PRODUCTION = REGISTRATE.multiblock("general_ae_production", WorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .appearanceBlock(() -> GetRegistries.getBlock("ae2:sky_stone_block"))
            .recipeType(RTTGTRecipeTypes.GENERAL_AE_PRODUCTION)
            .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK_SUBTICK))
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("AAAAAAAAA", "CCCCCCCCC", "         ", "         ", "         ", "         ", "         ", "         ")
                    .aisle("AAAAAAAAA", "C       C", "         ", "         ", "         ", "         ", "         ", "         ")
                    .aisle("AAAAAAAAA", "C D C D C", "  D C D  ", "  D D D  ", "  E E E  ", "    C    ", "         ", "         ")
                    .aisle("AAAAAAAAA", "C       C", "         ", "    C    ", "         ", "    C    ", "         ", "         ")
                    .aisle("AAAAAAAAA", "C C C C C", "  C F C  ", "  DCDCD  ", "  E E E  ", "  CCECC  ", "    E    ", "    C    ")
                    .aisle("AAAAAAAAA", "C       C", "         ", "    C    ", "         ", "    C    ", "         ", "         ")
                    .aisle("AAAAAAAAA", "C D C D C", "  D C D  ", "  D D D  ", "  E E E  ", "    C    ", "         ", "         ")
                    .aisle("AAAAAAAAA", "C       C", "         ", "         ", "         ", "         ", "         ", "         ")
                    .aisle("AAAA~AAAA", "CCCCCCCCC", "         ", "         ", "         ", "         ", "         ", "         ")
                    .where("~", Predicates.controller(Predicates.blocks(definition.get())))
                    .where("C", Predicates.blocks(GetRegistries.getBlock("ae2:quartz_wall")))
                    .where("D", Predicates.blocks(GetRegistries.getBlock("ae2:sky_stone_block")))
                    .where("F", Predicates.blocks(GetRegistries.getBlock("minecraft:anvil")))
                    .where("E", Predicates.blocks(GetRegistries.getBlock("ae2:fluix_block")))
                    .where("A", Predicates.blocks(GetRegistries.getBlock("ae2:sky_stone_block"))
                            .setMinGlobalLimited(10)
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)))
                    .build())
            .workableCasingRenderer(AppEng.makeId("block/sky_stone_block"),
                    GTCEu.id("block/multiblock/fusion_reactor"))
            .tooltips(Component.translatable("block.rttgtcore.general_ae_production.tooltip"))
            .register();
}
