modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = false
versionRange = "[1,)"
ordering = "BEFORE"
side = "BOTH"